import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from "next/font/google";
import Nav from "@/components/Nav";
import { Toaster } from "@/components/ui/sonner";

const rubik = Rubik({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${rubik.className} antialiased bg-slate-900 min-h-screen pt-8`}
            >
                <Nav />
                <Toaster
                    toastOptions={{
                        style: {
                            background: "rgb(30,41,59,1)",
                            color: "white",
                        },
                    }}
                    className=""
                />
                {children}
            </body>
        </html>
    );
}
